import type { ApiRoom, ApiSeries, ApiTournament } from './types';

/**
 * Full reference dataset served by the API and used to bootstrap the store.
 * Mirrors the app's bundled seed so the live API is complete on day one.
 * Ingestion adapters (adapters.ts) replace and extend this over time.
 */

const V = '2026-03-30';

export const BOOTSTRAP_ROOMS: ApiRoom[] = [
  { id: 'room-wynn', name: 'Wynn Poker Room', casino: 'Wynn / Encore', city: 'Las Vegas', state: 'NV', country: 'USA', region: 'LV Strip', tableCount: 28, stakesSpread: '1/3, 2/5, 5/10, 10/20', rake: { percent: 10, cap: 5, increments: 1, noFlopNoDrop: true, promoDrop: 0, buyInCap: 1500 }, compPerHour: 1, loyalty: 'Wynn Rewards', hoursOpen: '24/7', lat: 36.1264, lng: -115.1656, sourceUrl: 'https://www.wynnlasvegas.com/casino/poker', lastVerified: V, notes: 'No jackpot or high-hand drop, so no dead money off your pots. Highest buy-in caps on the Strip. Strong structural EV for serious players.' },
  { id: 'room-bellagio', name: 'Bellagio Poker Room', casino: 'Bellagio', city: 'Las Vegas', state: 'NV', country: 'USA', region: 'LV Strip', tableCount: 37, stakesSpread: '1/3, 2/5, 5/10, 10/20, 20/40', rake: { percent: 10, cap: 5, increments: 1, noFlopNoDrop: true, promoDrop: 1, buyInCap: 1500 }, compPerHour: 2, loyalty: 'MGM Rewards', hoursOpen: '24/7', lat: 36.1126, lng: -115.1767, sourceUrl: 'https://bellagio.mgmresorts.com/en/casino/poker.html', lastVerified: V, notes: "Automatic rake reduction when shorthanded. About $2/hr food comp. 37 tables including the high-stakes Bobby's Room." },
  { id: 'room-aria', name: 'Aria Poker Room', casino: 'Aria', city: 'Las Vegas', state: 'NV', country: 'USA', region: 'LV Strip', tableCount: 24, stakesSpread: '1/3, 2/5, 5/10, PLO', rake: { percent: 10, cap: 5, increments: 1, noFlopNoDrop: true, promoDrop: 1, buyInCap: 1500 }, compPerHour: 3, loyalty: 'MGM Rewards', hoursOpen: '24/7', lat: 36.1075, lng: -115.1763, sourceUrl: 'https://aria.mgmresorts.com/en/casino/poker.html', lastVerified: V, notes: 'Frequently cited best comps in town. A PLO hub. Fair rake.' },
  { id: 'room-venetian', name: 'Venetian Poker Room', casino: 'Venetian', city: 'Las Vegas', state: 'NV', country: 'USA', region: 'LV Strip', tableCount: 50, stakesSpread: '1/2, 1/3, 2/5, 5/10', rake: { percent: 10, cap: 5, increments: 1, noFlopNoDrop: true, promoDrop: 1, buyInCap: 1500 }, compPerHour: 1.5, loyalty: 'Venetian Rewards', hoursOpen: '24/7', lat: 36.1212, lng: -115.1697, sourceUrl: 'https://www.venetianlasvegas.com/casino/poker.html', lastVerified: V, notes: 'Largest room on the Strip (~50 tables). Most tournaments per week with strong DeepStack structures.' },
  { id: 'room-caesars', name: 'Caesars Palace Poker Room', casino: 'Caesars Palace', city: 'Las Vegas', state: 'NV', country: 'USA', region: 'LV Strip', tableCount: 12, stakesSpread: '1/3, 2/5', rake: { percent: 10, cap: 5, increments: 1, noFlopNoDrop: true, promoDrop: 1, buyInCap: 1000 }, compPerHour: 1.5, loyalty: 'Caesars Rewards', hoursOpen: '24/7', lat: 36.1162, lng: -115.1745, sourceUrl: 'https://www.caesars.com/caesars-palace/casino', lastVerified: V, notes: 'Active Strip room. Confirm current spread and rake at ingestion.' },
  { id: 'room-horseshoe', name: 'Horseshoe Poker Room', casino: 'Horseshoe Las Vegas', city: 'Las Vegas', state: 'NV', country: 'USA', region: 'LV Strip', tableCount: 10, stakesSpread: '1/3, 2/5', rake: { percent: 10, cap: 5, increments: 1, noFlopNoDrop: true, promoDrop: 1, buyInCap: 1000 }, compPerHour: 1, loyalty: 'Caesars Rewards', hoursOpen: '24/7', lat: 36.1146, lng: -115.1728, sourceUrl: 'https://www.caesars.com/horseshoe-las-vegas', lastVerified: V, notes: "Formerly Bally's. Co-hosts the World Series of Poker with Paris each summer." },
  { id: 'room-mgm-grand', name: 'MGM Grand Poker Room', casino: 'MGM Grand', city: 'Las Vegas', state: 'NV', country: 'USA', region: 'LV Strip', tableCount: 11, stakesSpread: '1/2, 1/3, 2/5', rake: { percent: 10, cap: 5, increments: 1, noFlopNoDrop: true, promoDrop: 1, buyInCap: 1000 }, compPerHour: 1, loyalty: 'MGM Rewards', hoursOpen: '24/7', lat: 36.1023, lng: -115.1697, sourceUrl: 'https://mgmgrand.mgmresorts.com/en/casino/poker.html', lastVerified: V, notes: 'Active Strip room. Confirm current spread and rake at ingestion.' },
  { id: 'room-mandalay', name: 'Mandalay Bay Poker Room', casino: 'Mandalay Bay', city: 'Las Vegas', state: 'NV', country: 'USA', region: 'LV Strip', tableCount: 9, stakesSpread: '1/2, 1/3, 2/5', rake: { percent: 10, cap: 5, increments: 1, noFlopNoDrop: true, promoDrop: 1, buyInCap: 1000 }, compPerHour: 1, loyalty: 'MGM Rewards', hoursOpen: '24/7', lat: 36.0918, lng: -115.1769, sourceUrl: 'https://mandalaybay.mgmresorts.com/en/casino.html', lastVerified: V, notes: 'Active Strip room at the south end. Confirm current spread and rake at ingestion.' },
  { id: 'room-borgata', name: 'Borgata Poker Room', casino: 'Borgata', city: 'Atlantic City', state: 'NJ', country: 'USA', region: 'Atlantic City', tableCount: 65, stakesSpread: '1/2, 2/5, 5/10', rake: { percent: 10, cap: 4, increments: 1, noFlopNoDrop: true, promoDrop: 1, buyInCap: 600 }, compPerHour: 1, loyalty: 'MGM Rewards', hoursOpen: '24/7', lat: 39.3797, lng: -74.4399, sourceUrl: 'https://borgata.mgmresorts.com/en/casino/poker.html', lastVerified: V, notes: 'The dominant Atlantic City room and East Coast tournament hub. AC caps and drops differ from Vegas; verify at ingestion.' },
  { id: 'room-harrahs-ac', name: "Harrah's AC Poker Room", casino: "Harrah's Resort Atlantic City", city: 'Atlantic City', state: 'NJ', country: 'USA', region: 'Atlantic City', tableCount: 20, stakesSpread: '1/2, 2/5', rake: { percent: 10, cap: 4, increments: 1, noFlopNoDrop: true, promoDrop: 1, buyInCap: 500 }, compPerHour: 1, loyalty: 'Caesars Rewards', hoursOpen: '24/7', lat: 39.3826, lng: -74.4361, sourceUrl: 'https://www.caesars.com/harrahs-ac', lastVerified: V, notes: 'Hosts WSOP Circuit stops. Verify current rake and structure at ingestion.' },
  { id: 'room-trop-ac', name: 'Tropicana AC Poker Room', casino: 'Tropicana Atlantic City', city: 'Atlantic City', state: 'NJ', country: 'USA', region: 'Atlantic City', tableCount: 16, stakesSpread: '1/2, 2/5', rake: { percent: 10, cap: 4, increments: 1, noFlopNoDrop: true, promoDrop: 1, buyInCap: 500 }, compPerHour: 1, loyalty: 'Caesars Rewards', hoursOpen: '24/7', lat: 39.3526, lng: -74.4419, sourceUrl: 'https://www.tropicana.net', lastVerified: V, notes: 'Atlantic City room. Verify current spread and rake at ingestion.' },
  { id: 'room-hardrock-ac', name: 'Hard Rock AC Poker Room', casino: 'Hard Rock Atlantic City', city: 'Atlantic City', state: 'NJ', country: 'USA', region: 'Atlantic City', tableCount: 22, stakesSpread: '1/2, 2/5, 5/10', rake: { percent: 10, cap: 4, increments: 1, noFlopNoDrop: true, promoDrop: 1, buyInCap: 600 }, compPerHour: 1, loyalty: 'Hard Rock Unity', hoursOpen: '24/7', lat: 39.3576, lng: -74.4339, sourceUrl: 'https://www.hardrockhotelatlanticcity.com', lastVerified: V, notes: 'Atlantic City room. Verify current spread and rake at ingestion.' },
];

export const BOOTSTRAP_SERIES: ApiSeries[] = [
  { id: 'series-wsop-2026', name: 'World Series of Poker 2026', organizer: 'WSOP', startDate: '2026-05-26', endDate: '2026-07-15', city: 'Las Vegas', country: 'USA', year: 2026, venueRoomName: 'Horseshoe & Paris Las Vegas', sourceUrl: 'https://www.wsop.com', lastVerified: V, tentative: false },
  { id: 'series-wpt-s24', name: 'WPT Season 24', organizer: 'World Poker Tour', startDate: '2026-01-06', endDate: '2026-12-20', city: 'Multiple', country: 'USA', year: 2026, venueRoomName: 'Various', sourceUrl: 'https://www.wpt.com', lastVerified: V, tentative: false },
  { id: 'series-wsopc-2026', name: 'WSOP Circuit 2026', organizer: 'WSOP Circuit', startDate: '2026-07-15', endDate: '2026-08-24', city: 'Multiple', country: 'USA', year: 2026, venueRoomName: 'Various', sourceUrl: 'https://www.wsop.com/circuit', lastVerified: V, tentative: false },
  { id: 'series-wsop-2027', name: 'World Series of Poker 2027', organizer: 'WSOP', startDate: '2027-05-25', endDate: '2027-07-14', city: 'Las Vegas', country: 'USA', year: 2027, venueRoomName: 'Horseshoe & Paris Las Vegas', sourceUrl: 'https://www.wsop.com', lastVerified: V, tentative: true },
];

export const BOOTSTRAP_TOURNAMENTS: ApiTournament[] = [
  { id: 't-wpt-luckyhearts', seriesId: 'series-wpt-s24', name: 'WPT Lucky Hearts Poker Open Championship', roomName: 'Seminole Hard Rock Hollywood', city: 'Hollywood, FL', buyIn: 3500, guarantee: 2000000, gameType: 'NLHE', format: 'tournament', startDateTime: '2026-01-16T12:00:00', lateRegLevel: 'End of Day 1', structureUrl: 'https://www.wpt.com', sourceUrl: 'https://www.wpt.com', status: 'completed', lastVerified: V, tentative: false },
  { id: 't-wpt-venetian-spring', seriesId: 'series-wpt-s24', name: 'WPT Venetian Spring Championship', roomName: 'Venetian Las Vegas', city: 'Las Vegas, NV', buyIn: 5000, guarantee: 2000000, gameType: 'NLHE', format: 'tournament', startDateTime: '2026-02-20T11:00:00', lateRegLevel: 'Level 12', structureUrl: 'https://www.venetianlasvegas.com', sourceUrl: 'https://www.wpt.com', status: 'completed', lastVerified: V, tentative: false },
  { id: 't-wsop-mysterymillions', seriesId: 'series-wsop-2026', name: 'WSOP Event #1: $1,000 Mystery Millions', roomName: 'Horseshoe Las Vegas', city: 'Las Vegas, NV', buyIn: 1000, guarantee: 5000000, gameType: 'NLHE', format: 'tournament', startDateTime: '2026-05-26T10:00:00', lateRegLevel: 'End of Day 1', structureUrl: 'https://www.wsop.com', sourceUrl: 'https://www.wsop.com', status: 'running', lastVerified: V, tentative: false },
  { id: 't-wsop-monsterstack', seriesId: 'series-wsop-2026', name: 'WSOP $1,500 Monster Stack', roomName: 'Paris Las Vegas', city: 'Las Vegas, NV', buyIn: 1500, guarantee: null, gameType: 'NLHE', format: 'tournament', startDateTime: '2026-06-19T10:00:00', lateRegLevel: 'End of Day 1', structureUrl: 'https://www.wsop.com', sourceUrl: 'https://www.wsop.com', status: 'scheduled', lastVerified: V, tentative: false },
  { id: 't-wsop-ppc', seriesId: 'series-wsop-2026', name: 'WSOP $50,000 Poker Players Championship', roomName: 'Horseshoe Las Vegas', city: 'Las Vegas, NV', buyIn: 50000, guarantee: null, gameType: 'Mixed', format: 'tournament', startDateTime: '2026-06-24T14:00:00', lateRegLevel: 'Level 6', structureUrl: 'https://www.wsop.com', sourceUrl: 'https://www.wsop.com', status: 'scheduled', lastVerified: V, tentative: false },
  { id: 't-wsop-mainevent', seriesId: 'series-wsop-2026', name: 'WSOP $10,000 Main Event', roomName: 'Horseshoe & Paris Las Vegas', city: 'Las Vegas, NV', buyIn: 10000, guarantee: null, gameType: 'NLHE', format: 'tournament', startDateTime: '2026-07-02T10:00:00', lateRegLevel: 'End of Day 2', structureUrl: 'https://www.wsop.com', sourceUrl: 'https://www.wsop.com', status: 'scheduled', lastVerified: V, tentative: false },
  { id: 't-wsopc-choctaw', seriesId: 'series-wsopc-2026', name: 'WSOP Circuit Choctaw Durant Main Event', roomName: 'Choctaw Casino Durant', city: 'Durant, OK', buyIn: 1700, guarantee: 1000000, gameType: 'NLHE', format: 'tournament', startDateTime: '2026-07-24T11:00:00', lateRegLevel: 'End of Day 1', structureUrl: 'https://www.wsop.com/circuit', sourceUrl: 'https://www.wsop.com/circuit', status: 'scheduled', lastVerified: V, tentative: false },
  { id: 't-wsopc-cherokee', seriesId: 'series-wsopc-2026', name: "WSOP Circuit Harrah's Cherokee Main Event", roomName: "Harrah's Cherokee", city: 'Cherokee, NC', buyIn: 1700, guarantee: 1500000, gameType: 'NLHE', format: 'tournament', startDateTime: '2026-08-14T11:00:00', lateRegLevel: 'End of Day 1', structureUrl: 'https://www.wsop.com/circuit', sourceUrl: 'https://www.wsop.com/circuit', status: 'scheduled', lastVerified: V, tentative: false },
  { id: 't-wsopc-ac', seriesId: 'series-wsopc-2026', name: "WSOP Circuit Harrah's Atlantic City Main Event", roomName: "Harrah's Resort Atlantic City", city: 'Atlantic City, NJ', buyIn: 1700, guarantee: 1000000, gameType: 'NLHE', format: 'tournament', startDateTime: '2026-08-21T11:00:00', lateRegLevel: 'End of Day 1', structureUrl: 'https://www.wsop.com/circuit', sourceUrl: 'https://www.wsop.com/circuit', status: 'scheduled', lastVerified: V, tentative: false },
  { id: 't-wpt-worldchamp', seriesId: 'series-wpt-s24', name: 'WPT World Championship', roomName: 'Wynn Las Vegas', city: 'Las Vegas, NV', buyIn: 10400, guarantee: 15000000, gameType: 'NLHE', format: 'tournament', startDateTime: '2026-12-08T11:00:00', lateRegLevel: 'Day 2', structureUrl: 'https://www.wpt.com', sourceUrl: 'https://www.wpt.com', status: 'scheduled', lastVerified: V, tentative: false },
  { id: 't-wsop-2027-main', seriesId: 'series-wsop-2027', name: 'WSOP $10,000 Main Event (tentative)', roomName: 'Horseshoe & Paris Las Vegas', city: 'Las Vegas, NV', buyIn: 10000, guarantee: null, gameType: 'NLHE', format: 'tournament', startDateTime: '2027-07-01T10:00:00', lateRegLevel: 'End of Day 2', structureUrl: 'https://www.wsop.com', sourceUrl: 'https://www.wsop.com', status: 'scheduled', lastVerified: V, tentative: true },
];
